<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="CRKRL-GULLLFAR1" failures="1" tests="2" name="Test" time="17.827" errors="0" timestamp="2020-02-29T22:05:39 PKT">
  <testcase classname="example.NewTest" name="testwithGroup" time="11.491">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at example.NewTest.testwithGroup(NewTest.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testwithGroup -->
  <testcase classname="example.NewTest" name="SecondtestwithGroup" time="11.497"/>
  <testcase classname="example.NewTest" name="testwithoutGroup" time="0.0">
    <ignored/>
  </testcase> <!-- testwithoutGroup -->
</testsuite> <!-- Test -->
